# Backporting Github Actions that ports a given PR to specified branch (via backport branch_name label) if the following conditions are met:
# 1) The PR is merged
# 2) The PR has a label of "backport branch_name" and branch_name is an existing branch.
# The label can be specified before or after the original PR is merged. Once these two conditions are met the bot will open a backport PR.
name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
